#postGre
spring.application.name=DeciBel
server.port=8081
spring.datasource.url=jdbc:postgresql://localhost:5332/DeciBel
spring.datasource.username=DeciBel
spring.datasource.password=DeciBel1234
#updates tables to match on each run
spring.jpa.hibernate.ddl-auto=update

#hibernate & jpa settings 
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

#cassandra settings
spring.cassandra.contact-points=cassandra
spring.cassandra.port=9042
spring.cassandra.keyspace-name=decibel
spring.cassandra.local-datacenter=datacenter1

# Schema management
spring.cassandra.schema-action=create_if_not_exists

# Startup behavior
spring.cassandra.connection.connect-timeout=10s
spring.cassandra.connection.init-query-timeout=10s
