#postGre
spring.application.name=DeciBel
spring.profiles.active=dev
server.port=8081
spring.datasource.url=jdbc:postgresql://localhost:5332/DeciBel
spring.datasource.username=DeciBel
spring.datasource.password=DeciBel1234
#updates tables to match on each run
spring.jpa.hibernate.ddl-auto=update
#hibernate & jpa settings
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
#base url for frontend
app.frontend-base-url=https://decibel.foo
# google oauth
app.google.redirect-uri=http://localhost:8081

# --- WEB ---
spring.security.oauth2.client.registration.google-web.provider=google
spring.security.oauth2.client.registration.google-web.client-id=122799926632-oib5to3n28ibprcrp3eji72o8d7rvd5i.apps.googleusercontent.com
spring.security.oauth2.client.registration.google-web.client-secret=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
spring.security.oauth2.client.registration.google-web.redirect-uri=6Ldh3posAAAAAIQHDNnrnu0YpNjZGaW4XBWk05jY

# --- DESKTOP ---
spring.security.oauth2.client.registration.google-desktop.provider=google
spring.security.oauth2.client.registration.google-desktop.client-id=122799926632-1bfq4bmfiv50709vije7l0m8lorcm5a0.apps.googleusercontent.com
spring.security.oauth2.client.registration.google-desktop.client-secret=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
spring.security.oauth2.client.registration.google-desktop.redirect-uri=http://localhost:8081/login/oauth2/code/google-desktop

# --- MOBILE ---
spring.security.oauth2.client.registration.google-mobile.provider=google
spring.security.oauth2.client.registration.google-mobile.client-id=122799926632-u4k8scr5stqr8k41tk42ssjikjd5a7ih.apps.googleusercontent.com
spring.security.oauth2.client.registration.google-mobile.redirect-uri=http://localhost:8081/login/oauth2/code/google-mobile

#--- STRIPE ---
stripe.api.key=${STRIPE_API_KEY:}
stripe.price.pro.id=${STRIPE_PRICE_PRO_ID:}
stripe.webhook.secret=${WEBHOOK_SECRET:}

#--- FireBase ---
firebase.service-account-path=firebase-service-account.json

#--- migrations ---
spring.flyway.enabled=false
spring.flyway.baseline-on-migrate=true
spring.flyway.baseline-version=1

#mail configuration  to email reset password link
#decibel
#password Decibel1234
#gmail decibel268@gmail.com
#gosp qsnv nptg knhm
#for production change it
app.cors.allowed-origins=*
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=decibel268@gmail.com
spring.mail.password=gosp qsnv nptg knhm
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
server.tomcat.max-part-count=50
server.servlet.context-path=/api
app.mail.from=<your-email>
# Forces TLS upgrade on connection ? no silent fallback to plain text
spring.mail.properties.mail.smtp.starttls.required=true
# Trusts Gmail's SMTP certificate explicitly ? fixes PKIX path building SSL error
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
# File upload and requests
# We will increase threshold so that max size can be handled and validated using business logic not here
spring.servlet.multipart.max-file-size=1000MB
spring.servlet.multipart.max-request-size=2500MB
#Microsoft azure
azure.storage.connection-string=BlobEndpoint=https://decibelblob.blob.core.windows.net;SharedAccessSignature=sp=racwdl&st=2026-03-15T13:47:33Z&se=2026-06-15T21:02:33Z&spr=https&sv=2024-11-04&sr=c&sig=jQNYGuR5D5CUqsv51i47U0nadH1d7w2wcUXaDC34HtM%3D
azure.storage.blob-container-name=uploads
#captcha bypassing
captcha.bypass-token=test_bypass_123