#postGre
spring.application.name=DeciBel
server.port=8081
spring.datasource.url=jdbc:postgresql://localhost:5332/DeciBel
spring.datasource.username=DeciBel
spring.datasource.password=DeciBel1234
#updates tables to match on each run
spring.jpa.hibernate.ddl-auto=update

#hibernate & jpa settings 
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
