services:
  postgres:
    image: postgres:latest
    container_name: DeciBel-postgres
    environment:
      POSTGRES_USER: DeciBel
      POSTGRES_PASSWORD: DeciBel1234
      POSTGRES_DB: DeciBel
      PGDATA: /data/postgres
    volumes:
      - postgres_data:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - backend
    restart: unless-stopped

networks:
  backend:
    driver: bridge

volumes:
  postgres_data:
