name: Backend CI/CD

on:
  push:
    branches: [ "main", "Dev" ]
  pull_request:
    branches: [ "main", "Dev" ]

env:
  JAVA_VERSION: '25'

jobs:
  test-and-verify:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: DeciBel

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: '${{ env.JAVA_VERSION }}'
          distribution: 'temurin'
          cache: 'maven'
          cache-dependency-path: 'DeciBel/pom.xml'

      - name: Make mvnw executable
        run: chmod +x mvnw

      - name: Run Tests and Compile
        run: ./mvnw verify
